### ISSUE TITLE
net/service

### ISSUE THREAD

**Issue by antiyro** [KasarLabs/barknet#19]
Implement bitcoin-da to Substrate full node via servie.rs: https://github.com/KasarLabs/net/blob/3720836791141854ff88f96bc4b04fb76d10294e/crates/node/src/service.rs#L400

**Comment by eytanlvy** [comment]
I'll take it @antiyro

**Comment by 0xEniotna** [comment]
Can you please do #da/clean_repo (cant link issue idk why)
